[package]
name = "stabilizer-streaming"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
num_enum = "0.5"
log = "0.4"
env_logger = "0.9"
async-std = { version = "1", features = ["attributes"] }
tide = "0.16"
serde = {version = "1", features = ["derive"]}

[build-dependencies]
npm_rs = "0.2.1"
